import type { DashboardRawData } from "../dashboardDataAssembler";

export interface DashboardViewData extends DashboardRawData {
  sessionCount: number;
  today: { costUsd: number; credits: number; turns: number };
  week: { costUsd: number; credits: number; turns: number };
  usagePct: string;
  daysRemaining: number;
  dailyBudgetRemaining: string;
  burnRate: number;
  projectedPeriodCredits: number;
  forecastVisible: boolean;
  forecastOverage: number;
  avgResponseLabel: string;
  totalBillableInput30d: number;
  avgInputPerTurn: number;
  cacheHitColor: string;
  avgInputStyle: string;
  avgInputNote: string;
  errorStyle: string;
  errorNote: string;
  ioRatioLabel: string;
  alertCardsHtml: string;
  playbookRowsHtml: string;
  surfaceCostTableHtml: string;
  estHoursSaved: string;
  costPerOutputK: string;
  outputTokensK: string;
  inputOverheadPct: string;
  workspaceSummaryView: {
    topWorkspaceLabel: string;
    topWorkspaceCostUsd: number;
    topWorkspaceSessions: number;
    workspaceRowsHtml: string;
    lastUpdatedMs: number;
  };
  recentSessionRowsHtml: string;
  freshnessLabel: string;
  unknownModelBannerHtml: string;
  cacheSavingsView: {
    hasSavings: boolean;
    savingsCostUsd: string;
    savingsCredits: string;
    savingsPct: string;
    topModelRows: string;
  };
  surfaceCostView: Array<{ label: string; costUsd: number; credits: number; turnCount: number; pct: number }>;
  dailyLabels: string;
  dailyData: string;
  dailyCreditsData: string;
  modelLabels: string;
  modelCostData: string;
  modelTurnData: string;
  modelPctData: string;
  agentBreakdownData: string;
  dailyAgentBreakdownData: string;
  heatmapData: string;
  dailyRangeSeriesJson: string;
  sessionsJson: string;
  turnDiscoveryJson: string;
  agentLabelMapJson: string;
  ioRatioLabels: string;
  ioNetInput: string;
  ioCached: string;
  ioOutput: string;
  surfaceLabels: string;
  surfaceInputs: string;
  surfaceCostLabels: string;
  surfaceCostData: string;
  modelDataByPeriodJson: string;
  budgetCredits: number;
  billingPeriodStartMs: number;
  nonce: string;
  cspSource: string;
}

export { renderOverviewTab } from "./overviewTab";
export { renderBudgetTab } from "./budgetTab";
export { renderSessionsTab } from "./sessionsTab";
export { renderModelsTab } from "./modelsTab";
export { renderTokensTab } from "./tokensTab";
export { renderInsightsTab } from "./insightsTab";
export { renderEstimatesTab } from "./estimatesTab";
export { renderDashboardScript } from "./dashboardScript";
export { renderDashboardHeader } from "./dashboardHeader";
